# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
services:
  pulumi_mo:
    entrypoint: ["sleep", "infinity"]
    build: .
    environment:
      # MO
      FASTRAMQPI__AMQP__URL: "amqp://guest:guest@msg-broker"
      FASTRAMQPI__AUTH_SERVER: "http://keycloak:8080/auth"
      FASTRAMQPI__MO_URL: "http://mo:5000"
      FASTRAMQPI__CLIENT_ID: "dipex"
      FASTRAMQPI__CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"

      # Database
      FASTRAMQPI__DATABASE__USER: "pulumi_mo"
      FASTRAMQPI__DATABASE__PASSWORD: "pulumi_mo"
      FASTRAMQPI__DATABASE__HOST: "db"
      FASTRAMQPI__DATABASE__NAME: "pulumi_mo"
    volumes:
      - ./pulumi_mo/:/app/pulumi_mo:ro
      - ./tests/:/app/tests/:ro
      # Demo mapping
      - ./docker/entrypoint.sh:/app/entrypoint.sh:ro
      - ./docker/demo/Pulumi.yaml:/app/Pulumi.yaml:ro
      - ./docker/demo/__main__.py:/app/__main__.py:ro
      - ../pulumi/import/data:/opt/data:ro
    networks:
      - default
      - os2mo_default

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: "pulumi_mo"
      POSTGRES_PASSWORD: "pulumi_mo"
      POSTGRES_DB: "pulumi_mo"
    networks:
      - default

networks:
  os2mo_default:
    external: true
