# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
[tool.poetry]
name = "pulumi_mo"
version = "0.0.0"  # versioning handled by conventional commits
description = "Dynamic Pulumi provider for OS2mo"
authors = ["Magenta ApS <info@magenta.dk>"]
license = "MPL-2.0"
readme = "README.md"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/pulumi_mo"
keywords = ["os2mo"]
packages = [ { include = "pulumi_mo" } ]
include = ["pulumi_mo/py.typed"]

[tool.poetry.dependencies]
python = "^3.11"
pulumi = "^3"
fastramqpi = "^12"
httpx = ">=0.27,<0.29"
pydantic = "^1"

[tool.poetry.group.test.dependencies]
pytest = "^8"
pytest-asyncio = "^0.24"
pytest-cov = "^5"
pytest-split = "^0.9"
pytest-xdist = "^3"

[tool.poetry.group.pre-commit.dependencies]
pre-commit = "^3"
ruff = "^0.9"
deptry = "^0.23"
mypy = "^1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode="auto"

[tool.mypy]
python_version = "3.11"
warn_return_any = "True"
warn_unused_configs = "True"
check_untyped_defs = "True"
disallow_untyped_defs = "True"

[[tool.mypy.overrides]]
# Mypy doesn't understand the pylint ignore
module = "pulumi_mo.autogenerated_graphql_client.*"
disallow_untyped_defs = "False"

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
extend-select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I"

]
ignore = [
  # Allow lines longer than 90 characters if ruff-format decides so
  "E501"
]

[tool.ruff.lint.isort]
force-single-line = true

[tool.coverage.report]
omit = [
  "pulumi_mo/autogenerated_graphql_client/*",
]

[tool.ariadne-codegen]
# The default package name is `graphql_client`. Make it more obvious that the
# files are not to be modified manually.
target_package_name = "autogenerated_graphql_client"
target_package_path = "pulumi_mo/"
client_name = "GraphQLClient"
async_client = false
schema_path = "schema.graphql"  # curl -O http://localhost:5000/graphql/v25/schema.graphql
queries_path = "queries"
include_all_inputs = false
include_all_enums = false
include_comments = false
plugins = [
    # Return values directly when only a single top field is requested
    "ariadne_codegen.contrib.shorter_results.ShorterResultsPlugin",
    # Add UNSET and UnsetType to generated input types
    "fastramqpi.ariadne.UnsetInputTypesPlugin",
]
[tool.ariadne-codegen.scalars.DateTime]
type = "datetime.datetime"
parse = "fastramqpi.ariadne.parse_graphql_datetime"
[tool.ariadne-codegen.scalars.UUID]
type = "uuid.UUID"
