# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from uuid import UUID

import pytest
from more_itertools import one
from pulumi.automation import ConfigMap
from pulumi.urn import _parse_urn as parse_urn

from pulumi_mo.autogenerated_graphql_client.client import GraphQLClient
from pulumi_mo.autogenerated_graphql_client.input_types import EmployeeFilter

from .conftest import StackBuilder


@pytest.mark.integration_test
def test_person(
    stack_builder: StackBuilder,
    mo_config_map: ConfigMap,
    graphql_client: GraphQLClient,
) -> None:
    result = graphql_client.person_read(filter=EmployeeFilter())
    assert result.objects == []

    def pulumi_program() -> None:
        from pulumi_mo.person import Person
        from pulumi_mo.person import PersonArgs

        Person("alya", PersonArgs("Alya", "Shadowsong"))

    with stack_builder(pulumi_program) as stack:
        stack.set_all_config(mo_config_map)

        up_res = stack.up()
        assert len(up_res.outputs) == 0
        assert up_res.summary.kind == "update"
        assert up_res.summary.result == "succeeded"

        result = graphql_client.person_read(filter=EmployeeFilter())
        alya = one(result.objects).current
        assert alya is not None
        assert alya.dict() == {"given_name": "Alya", "surname": "Shadowsong"}

        destroy_res = stack.destroy()
        assert destroy_res.summary.kind == "destroy"
        assert destroy_res.summary.result == "succeeded"

        result = graphql_client.person_read(filter=EmployeeFilter())
        assert result.objects == []


@pytest.mark.integration_test
def test_person_urn(
    stack_builder: StackBuilder,
    mo_config_map: ConfigMap,
    project_name: str,
    stack_identifier: str,
) -> None:
    def pulumi_program() -> None:
        from pulumi import export

        from pulumi_mo.person import Person
        from pulumi_mo.person import PersonArgs

        person = Person("alya", PersonArgs("Alya", "Shadowsong"))

        export("id", person.id)
        export("urn", person.urn)

    with stack_builder(pulumi_program) as stack:
        stack.set_all_config(mo_config_map)

        up_res = stack.up()
        assert up_res.outputs.keys() == {"id", "urn"}
        UUID(up_res.outputs["id"].value)

        urn = up_res.outputs["urn"].value
        purn = parse_urn(urn)
        assert purn.urn_name == "alya"
        assert purn.pkg_name == "pulumi-python"
        assert purn.mod_name == "dynamic"
        assert purn.typ_name == "Person"

        assert (
            urn
            == f"urn:pulumi:{stack_identifier}::{project_name}::{purn.pkg_name}:{purn.mod_name}:{purn.typ_name}::{purn.urn_name}"
        )
