# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from uuid import UUID

import pytest

from pulumi_mo.autogenerated_graphql_client.client import GraphQLClient


@pytest.mark.integration_test
def test_client(
    graphql_client: GraphQLClient,
) -> None:
    result = graphql_client.who_am_i()
    assert isinstance(result.actor.uuid, UUID)
