# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from unittest.mock import ANY

import pytest
from more_itertools import one
from pulumi.automation import ConfigMap

from pulumi_mo.autogenerated_graphql_client.client import GraphQLClient
from pulumi_mo.autogenerated_graphql_client.input_types import ITUserFilter

from .conftest import StackBuilder


@pytest.mark.integration_test
def test_ituser(
    stack_builder: StackBuilder,
    mo_config_map: ConfigMap,
    graphql_client: GraphQLClient,
) -> None:
    result = graphql_client.ituser_read(filter=ITUserFilter())
    assert result.objects == []

    def pulumi_program() -> None:
        from pulumi_mo.itsystem import ITSystem
        from pulumi_mo.itsystem import ITSystemArgs
        from pulumi_mo.ituser import ITUser
        from pulumi_mo.ituser import ITUserArgs
        from pulumi_mo.person import Person
        from pulumi_mo.person import PersonArgs

        alya = Person("alya", PersonArgs("Alya", "Shadowsong"))
        suila = ITSystem("suila", ITSystemArgs("suila"))
        ITUser("suila:alya", ITUserArgs("suila:alya", alya.id, suila.id))

    with stack_builder(pulumi_program) as stack:
        stack.set_all_config(mo_config_map)

        up_res = stack.up()
        assert len(up_res.outputs) == 0
        assert up_res.summary.kind == "update"
        assert up_res.summary.result == "succeeded"

        result = graphql_client.ituser_read(filter=ITUserFilter())
        alya = one(result.objects).current
        assert alya is not None
        assert alya.dict() == {
            "user_key": "suila:alya",
            "itsystem": {"uuid": ANY},
            "person": [{"uuid": ANY}],
        }

        destroy_res = stack.destroy()
        assert destroy_res.summary.kind == "destroy"
        assert destroy_res.summary.result == "succeeded"

        result = graphql_client.ituser_read(filter=ITUserFilter())
        assert result.objects == []
