# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from more_itertools import one
from pulumi import Config
from pulumi import Output
from pulumi import export

from pulumi_mo.autogenerated_graphql_client.input_types import FacetFilter
from pulumi_mo.base import create_graphql_client_from_config
from pulumi_mo.clazz import Class
from pulumi_mo.clazz import ClassArgs
from pulumi_mo.itsystem import ITSystem
from pulumi_mo.itsystem import ITSystemArgs
from pulumi_mo.ituser import ITUser
from pulumi_mo.ituser import ITUserArgs
from pulumi_mo.person import Person
from pulumi_mo.person import PersonArgs


def fetch_role_facet() -> str:
    graphql_client = create_graphql_client_from_config(Config())
    with graphql_client as session:
        result = session._testing_facet_read(filter=FacetFilter(user_keys=["role"]))
        facet = one(result.objects)
        return str(facet.uuid)


role_id = Output.from_input(fetch_role_facet())


admin = Class("admin", ClassArgs("admin", facet=role_id))
alya = Person("alya", PersonArgs("Alya", "Shadowsong"))
suila = ITSystem("suila", ITSystemArgs("Suila"))
ituser = ITUser("suila:alya", ITUserArgs("alya", alya.id, suila.id))


export("role_uuid", role_id)
export("admin_uuid", admin.id)
export("person_uuid", alya.id)
export("itsystem_uuid", suila.id)
export("ituser_uuid", ituser.id)
