# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
name: demo
description: A pulumi_mo example program.
runtime:
  name: python
  options:
    toolchain: poetry
