#!/usr/bin/env bash
# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

rm -rf pulumi_mo/autogenerated_graphql_client/
poetry run ariadne-codegen client
poetry run pre-commit run --files pulumi_mo/autogenerated_graphql_client/*
